### ISSUE TITLE
Zoom is not kept between restarts

### ISSUE THREAD

**Issue by MatMaul** [TheGoddessInari/rambox#93]
When leaving and relaunching Rambox the zoom configuration of services are lost, which is a bit of a pain.
I think it was also the case in unmaintained Rambox CE.

Fedora 29 + Gnome 3 X11.

**Comment by MatMaul** [comment]
Ok actually it is a bit worse than that :) Zoom is lost, but I also can only control the zoom of the first opened service. If I switch to another service and try ctrl maj + it zooms the first service.

**Comment by TheGoddessInari** [comment]
I've been trying to debug this, but Electron is making it a nightmare (and won't do any attachable debugging via vscode).

Does the following currently work?
* Right clicking on the tab for Zoom In, Zoom Out, Reset Zoom.
* Control + mousewheel while hovering over the tab specifically.

**Comment by MatMaul** [comment]
Both use cases are working perfectly fine.
Some wrong parameter in the keyboard shortcut ?

**Comment by MatMaul** [comment]
I am trying to debug too but it seems like I can't see my added console.log so it is a bit complicated ^^
The global "view" menu is the culprit here.

**Comment by TheGoddessInari** [comment]
It doesn't appear to be forwarding the command. I'll try later today to see if I can narrow down exactly what isn't forwarding. It goes from menu handler to main process (same as every other shortcut), main process to the appropriate webview.

IIRC the right click menu doesn't have to do any forwarding. This can be fixed, it's just weird that it's not behaving the same as **every** other menu entry, and investigating it has been a pain because of that.

**Comment by TheGoddessInari** [comment]
Try now @MatMaul. This looks to've been fixed in Electron 5.0. :)

**Comment by TheGoddessInari** [comment]
As mentioned previously, this should've been working all the way since back in May, **but**, the keyboard shortcuts don't work right, which I still need to resolve.

**Comment by MatMaul** [comment]
Yep seems fine outside of keyboard/mouse shortcuts. Since I know it I just do it on the tab if needed anyway now. Thanks.

**Comment by teras** [comment]
I have  a similar issue; actually zoom factor seems not to be able to change at all. When I press the keyboard shortcut, something seems to flash (I think) but nothing happens. Even tried to open the menu, still doesn't zoom. Any ideas?
